apiVersion: extensions/v1beta1
#apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: userlist-ingress
spec:
  rules:
  - host: userlist.universal-team-245015.gcp.com
    http:
      paths:
      - backend:
          serviceName: userlist-svc
          servicePort: 8181
