apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "userlist-hpa"
  namespace: "dev-song"
  labels:
    app: "userlist"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "userlist"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 50
  #targetCPUUtilizationPercentage: 50
