apiVersion: v1
kind: PersistentVolume
metadata:
  name: userlist-pv
  labels:
    app: userlist
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    #storage: 1Gi
    storage: 100Mi
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  gcePersistentDisk:
    fsType: ext4
    pdName: gke-standard-cluster-1-pvc-982517c1-9a81-11e9-a482-42010a8000a9
---

