apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: userlist-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      #storage: 1Gi
      storage: 100Mi
  #storageClassName: slow
  storageClassName: standard
  selector:
    matchLabels:
      app: userlist
    #matchExpressions:
    #  - {key: environment, operator: In, values: [dev]}
---
