apiVersion: v1
data:
  haproxy.cfg: |-
    global
        log         127.0.0.1 local0
        log         127.0.0.1 local1 notice
        maxconn     4000

    defaults
        balance roundrobin
        log     global
        mode    tcp
        option  tcplog
        option  redispatch
        option  log-health-checks
        retries 5
        maxconn 3000
        timeout connect 50s
        timeout client  1m
        timeout server  1m
        
    frontend  mainTest 
        bind *:80
        default_backend backserver
    
    backend backserver
        balance     roundrobin
        server  server1 35.170.216.115:80 check
        server  server2 35.170.216.115:80 check
kind: ConfigMap
metadata:
  labels:
    app: egress-1
    name: egress-1
  name: egress-1-cm
