apiVersion: v1
kind: Pod
metadata:
  name: frontend3
spec:
  containers:
  - name: db
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
  - name: wp
    image: wordpress
