apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-cli
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
      #annotations:
        #sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
