apiVersion: v1
kind: PersistentVolume
metadata:
  name: userlist-pv
  labels:
    app: userlist
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    #storage: 1Gi
    storage: 100Mi
  persistentVolumeReclaimPolicy: Recycle
  #storageClassName: standard
  gcePersistentDisk:
    fsType: ext4
    #### you have to create pd-disk named app-storage-1 before
    pdName: app-storage-1
---

